source :rubygems

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'
gem 'bcrypt-ruby'

gem 'shotgun'
gem 'rack-flash3'

group :development, :test do
  gem 'faker'
  gem 'rspec'
end
